### ISSUE TITLE
为啥把书都删了？？

### ISSUE THREAD

**Issue by CrazyStoneJy** [huihut/CS-Books#2]
为啥把书都删了？？

**Comment by huihut** [comment]
担心侵权😥

**Comment by zestloveheart** [comment]
留邮箱能打包发吗？谢谢大佬。zlh429375251@qq.com

**Comment by huihut** [comment]
[CS-Books-master.zip](https://github.com/huihut/CS-Books/archive/master.zip)

**Comment by zestloveheart** [comment]
# 谢谢
