### ISSUE TITLE
谢谢，有些书籍好像没有

### ISSUE THREAD

**Issue by Roc0010** [huihut/CS-Books#4]
比如C++ Primer 第五版（中文版）.pdf下载下来只有134b，还有很多书籍好像也是这样

**Comment by HuiTongGe** [comment]
我也发现了

**Comment by huihut** [comment]
百度网盘：https://pan.baidu.com/s/1gCBS7BhWmokx9Ks5FR-n5w 提取码：l2yp

**Comment by rongxuanhong** [comment]
链接已失效了，能更新下？
