### ISSUE TITLE
无法clone或下载

### ISSUE THREAD

**Issue by xmuwenxiang** [huihut/CS-Books#7]
每次下载到一大半就会出错，希望可以提供云盘的下载方式，多谢谢

**Comment by huihut** [comment]
百度网盘：https://pan.baidu.com/s/1OEwN3e_qrNPLm_4CkMDSng 提取码：v7rj

> <https://github.com/huihut/CS-Books#-computer-science-books-%E8%AE%A1%E7%AE%97%E6%9C%BA%E6%8A%80%E6%9C%AF%E7%B1%BB%E4%B9%A6%E7%B1%8D-pdf-%E6%96%87%E4%BB%B6>

**Comment by xmuwenxiang** [comment]
@huihut 多谢多谢。我尝试了其它方法，我将你的代码库克隆到码云了，这样在国内的下载速度很快，直接clone就可以了。https://gitee.com/xmuwenxiang/CS-Books.git
