### ISSUE TITLE
PDF 文件后缀问题

### ISSUE THREAD

**Issue by yuedou** [huihut/CS-Books#8]
hi， 以下内容的文件由于后缀与命名中间有空格，不能在github平台中对每个文件单独下载，希望fix。
- c++ primer 5th 中的文件

- unix 网络编程中的文件

- 根目录下的部分pdf文件

**Comment by huihut** [comment]
并不是因为空格，而是 LFS 空间不够，请移步百度网盘

1. 百度网盘1：链接：https://pan.baidu.com/s/1ZujRXFwqd7ZDf4V0nSogMw 提取码：hsb2    
2. 百度网盘2：链接：https://pan.baidu.com/s/1v5MMqeXZbliLHTXX3PaGhg  提取码：9q43

**Comment by tcxia** [comment]
The link above is no longer valid @huihut

**Comment by songapore** [comment]
> 并不是因为空格，而是 LFS 空间不够，请移步百度网盘
> 
> 1. 百度网盘1：链接：https://pan.baidu.com/s/1ZujRXFwqd7ZDf4V0nSogMw 提取码：hsb2
> 2. 百度网盘2：链接：https://pan.baidu.com/s/1v5MMqeXZbliLHTXX3PaGhg  提取码：9q43

您好，提示已取消分享，能重新分享一下吗

**Comment by bstsnail** [comment]
> > 并不是因为空格，而是 LFS 空间不够，请移步百度网盘
> > 
> > 1. 百度网盘1：链接：https://pan.baidu.com/s/1ZujRXFwqd7ZDf4V0nSogMw 提取码：hsb2
> > 2. 百度网盘2：链接：https://pan.baidu.com/s/1v5MMqeXZbliLHTXX3PaGhg  提取码：9q43
> 
> 您好，提示已取消分享，能重新分享一下吗

+1

**Comment by huihut** [comment]
太快挂了，现在百度网盘只放超过 100M 的大文件

链接：https://pan.baidu.com/s/1JhdhAbBja2O-lAZ2AN-ROQ 提取码：hdao
